[package]
name = "aardvark-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aardvark-ffi = { path = "aardvark-ffi" }
anyhow = "1.0.75"
